# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "feature/poc-starter" ]
  pull_request:
    branches: [ "feature/poc-starter" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x] # 16 and 18 removed- codebase refactor is required 
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Authenticate with private NPM package
      run: echo "@anagraph:registry=https://npm.pkg.github.com/" > ~/.npmrc
    - name: Add Auth Token to .npmrc
      run: echo "//npm.pkg.github.com/:_authToken=37768f02807ccc10d4c59da9628de167669cf52c" >> ~/.npmrc
    - run: npm ci
    - run: npm run build --if-present